spring:
  datasource:
    username: "testUser"
    password: "haslo123"
    url: "jdbc:mysql://localhost:3306/cryptoData"
    driver-class: "org.mysql.Driver"
  jpa:
    show-sql: false
security:
  keys:
    private_key: "MIICWgIBAAKBgGXp48R79lYGPH00D5Ud2HbsXeXf9AWKA/JAcTpYAk47ut2e5Heo"